package com.kim.model;

public class FctCustomerContract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.customer_id
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.customer_name
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.idcard_number
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String idcardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.customer_mobile_phone
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String customerMobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.customer_tel_phone
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String customerTelPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.customer_home_address
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String customerHomeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.customer_family_address
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String customerFamilyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.customer_company_address
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String customerCompanyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.contract_name
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String contractName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.contract_relation_ship
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String contractRelationShip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.contract_mobile_phone
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String contractMobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fct_customer_contract.remarks
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.customer_id
     *
     * @return the value of fct_customer_contract.customer_id
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.customer_id
     *
     * @param customerId the value for fct_customer_contract.customer_id
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.customer_name
     *
     * @return the value of fct_customer_contract.customer_name
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.customer_name
     *
     * @param customerName the value for fct_customer_contract.customer_name
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.idcard_number
     *
     * @return the value of fct_customer_contract.idcard_number
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getIdcardNumber() {
        return idcardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.idcard_number
     *
     * @param idcardNumber the value for fct_customer_contract.idcard_number
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setIdcardNumber(String idcardNumber) {
        this.idcardNumber = idcardNumber == null ? null : idcardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.customer_mobile_phone
     *
     * @return the value of fct_customer_contract.customer_mobile_phone
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getCustomerMobilePhone() {
        return customerMobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.customer_mobile_phone
     *
     * @param customerMobilePhone the value for fct_customer_contract.customer_mobile_phone
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setCustomerMobilePhone(String customerMobilePhone) {
        this.customerMobilePhone = customerMobilePhone == null ? null : customerMobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.customer_tel_phone
     *
     * @return the value of fct_customer_contract.customer_tel_phone
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getCustomerTelPhone() {
        return customerTelPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.customer_tel_phone
     *
     * @param customerTelPhone the value for fct_customer_contract.customer_tel_phone
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setCustomerTelPhone(String customerTelPhone) {
        this.customerTelPhone = customerTelPhone == null ? null : customerTelPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.customer_home_address
     *
     * @return the value of fct_customer_contract.customer_home_address
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getCustomerHomeAddress() {
        return customerHomeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.customer_home_address
     *
     * @param customerHomeAddress the value for fct_customer_contract.customer_home_address
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setCustomerHomeAddress(String customerHomeAddress) {
        this.customerHomeAddress = customerHomeAddress == null ? null : customerHomeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.customer_family_address
     *
     * @return the value of fct_customer_contract.customer_family_address
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getCustomerFamilyAddress() {
        return customerFamilyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.customer_family_address
     *
     * @param customerFamilyAddress the value for fct_customer_contract.customer_family_address
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setCustomerFamilyAddress(String customerFamilyAddress) {
        this.customerFamilyAddress = customerFamilyAddress == null ? null : customerFamilyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.customer_company_address
     *
     * @return the value of fct_customer_contract.customer_company_address
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getCustomerCompanyAddress() {
        return customerCompanyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.customer_company_address
     *
     * @param customerCompanyAddress the value for fct_customer_contract.customer_company_address
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setCustomerCompanyAddress(String customerCompanyAddress) {
        this.customerCompanyAddress = customerCompanyAddress == null ? null : customerCompanyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.contract_name
     *
     * @return the value of fct_customer_contract.contract_name
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getContractName() {
        return contractName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.contract_name
     *
     * @param contractName the value for fct_customer_contract.contract_name
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setContractName(String contractName) {
        this.contractName = contractName == null ? null : contractName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.contract_relation_ship
     *
     * @return the value of fct_customer_contract.contract_relation_ship
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getContractRelationShip() {
        return contractRelationShip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.contract_relation_ship
     *
     * @param contractRelationShip the value for fct_customer_contract.contract_relation_ship
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setContractRelationShip(String contractRelationShip) {
        this.contractRelationShip = contractRelationShip == null ? null : contractRelationShip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.contract_mobile_phone
     *
     * @return the value of fct_customer_contract.contract_mobile_phone
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getContractMobilePhone() {
        return contractMobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.contract_mobile_phone
     *
     * @param contractMobilePhone the value for fct_customer_contract.contract_mobile_phone
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setContractMobilePhone(String contractMobilePhone) {
        this.contractMobilePhone = contractMobilePhone == null ? null : contractMobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fct_customer_contract.remarks
     *
     * @return the value of fct_customer_contract.remarks
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fct_customer_contract.remarks
     *
     * @param remarks the value for fct_customer_contract.remarks
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}