package com.kim.model;

import java.util.ArrayList;
import java.util.List;

public class FctCustomerContractExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public FctCustomerContractExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(String value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(String value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(String value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(String value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(String value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(String value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLike(String value) {
            addCriterion("customer_id like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotLike(String value) {
            addCriterion("customer_id not like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<String> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<String> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(String value1, String value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(String value1, String value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNull() {
            addCriterion("customer_name is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNotNull() {
            addCriterion("customer_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameEqualTo(String value) {
            addCriterion("customer_name =", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotEqualTo(String value) {
            addCriterion("customer_name <>", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThan(String value) {
            addCriterion("customer_name >", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("customer_name >=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThan(String value) {
            addCriterion("customer_name <", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("customer_name <=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLike(String value) {
            addCriterion("customer_name like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotLike(String value) {
            addCriterion("customer_name not like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIn(List<String> values) {
            addCriterion("customer_name in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotIn(List<String> values) {
            addCriterion("customer_name not in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameBetween(String value1, String value2) {
            addCriterion("customer_name between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotBetween(String value1, String value2) {
            addCriterion("customer_name not between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberIsNull() {
            addCriterion("idcard_number is null");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberIsNotNull() {
            addCriterion("idcard_number is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberEqualTo(String value) {
            addCriterion("idcard_number =", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberNotEqualTo(String value) {
            addCriterion("idcard_number <>", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberGreaterThan(String value) {
            addCriterion("idcard_number >", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberGreaterThanOrEqualTo(String value) {
            addCriterion("idcard_number >=", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberLessThan(String value) {
            addCriterion("idcard_number <", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberLessThanOrEqualTo(String value) {
            addCriterion("idcard_number <=", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberLike(String value) {
            addCriterion("idcard_number like", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberNotLike(String value) {
            addCriterion("idcard_number not like", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberIn(List<String> values) {
            addCriterion("idcard_number in", values, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberNotIn(List<String> values) {
            addCriterion("idcard_number not in", values, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberBetween(String value1, String value2) {
            addCriterion("idcard_number between", value1, value2, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberNotBetween(String value1, String value2) {
            addCriterion("idcard_number not between", value1, value2, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneIsNull() {
            addCriterion("customer_mobile_phone is null");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneIsNotNull() {
            addCriterion("customer_mobile_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneEqualTo(String value) {
            addCriterion("customer_mobile_phone =", value, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneNotEqualTo(String value) {
            addCriterion("customer_mobile_phone <>", value, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneGreaterThan(String value) {
            addCriterion("customer_mobile_phone >", value, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("customer_mobile_phone >=", value, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneLessThan(String value) {
            addCriterion("customer_mobile_phone <", value, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("customer_mobile_phone <=", value, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneLike(String value) {
            addCriterion("customer_mobile_phone like", value, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneNotLike(String value) {
            addCriterion("customer_mobile_phone not like", value, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneIn(List<String> values) {
            addCriterion("customer_mobile_phone in", values, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneNotIn(List<String> values) {
            addCriterion("customer_mobile_phone not in", values, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneBetween(String value1, String value2) {
            addCriterion("customer_mobile_phone between", value1, value2, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("customer_mobile_phone not between", value1, value2, "customerMobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneIsNull() {
            addCriterion("customer_tel_phone is null");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneIsNotNull() {
            addCriterion("customer_tel_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneEqualTo(String value) {
            addCriterion("customer_tel_phone =", value, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneNotEqualTo(String value) {
            addCriterion("customer_tel_phone <>", value, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneGreaterThan(String value) {
            addCriterion("customer_tel_phone >", value, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("customer_tel_phone >=", value, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneLessThan(String value) {
            addCriterion("customer_tel_phone <", value, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneLessThanOrEqualTo(String value) {
            addCriterion("customer_tel_phone <=", value, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneLike(String value) {
            addCriterion("customer_tel_phone like", value, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneNotLike(String value) {
            addCriterion("customer_tel_phone not like", value, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneIn(List<String> values) {
            addCriterion("customer_tel_phone in", values, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneNotIn(List<String> values) {
            addCriterion("customer_tel_phone not in", values, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneBetween(String value1, String value2) {
            addCriterion("customer_tel_phone between", value1, value2, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerTelPhoneNotBetween(String value1, String value2) {
            addCriterion("customer_tel_phone not between", value1, value2, "customerTelPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressIsNull() {
            addCriterion("customer_home_address is null");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressIsNotNull() {
            addCriterion("customer_home_address is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressEqualTo(String value) {
            addCriterion("customer_home_address =", value, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressNotEqualTo(String value) {
            addCriterion("customer_home_address <>", value, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressGreaterThan(String value) {
            addCriterion("customer_home_address >", value, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressGreaterThanOrEqualTo(String value) {
            addCriterion("customer_home_address >=", value, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressLessThan(String value) {
            addCriterion("customer_home_address <", value, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressLessThanOrEqualTo(String value) {
            addCriterion("customer_home_address <=", value, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressLike(String value) {
            addCriterion("customer_home_address like", value, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressNotLike(String value) {
            addCriterion("customer_home_address not like", value, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressIn(List<String> values) {
            addCriterion("customer_home_address in", values, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressNotIn(List<String> values) {
            addCriterion("customer_home_address not in", values, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressBetween(String value1, String value2) {
            addCriterion("customer_home_address between", value1, value2, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerHomeAddressNotBetween(String value1, String value2) {
            addCriterion("customer_home_address not between", value1, value2, "customerHomeAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressIsNull() {
            addCriterion("customer_family_address is null");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressIsNotNull() {
            addCriterion("customer_family_address is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressEqualTo(String value) {
            addCriterion("customer_family_address =", value, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressNotEqualTo(String value) {
            addCriterion("customer_family_address <>", value, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressGreaterThan(String value) {
            addCriterion("customer_family_address >", value, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressGreaterThanOrEqualTo(String value) {
            addCriterion("customer_family_address >=", value, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressLessThan(String value) {
            addCriterion("customer_family_address <", value, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressLessThanOrEqualTo(String value) {
            addCriterion("customer_family_address <=", value, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressLike(String value) {
            addCriterion("customer_family_address like", value, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressNotLike(String value) {
            addCriterion("customer_family_address not like", value, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressIn(List<String> values) {
            addCriterion("customer_family_address in", values, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressNotIn(List<String> values) {
            addCriterion("customer_family_address not in", values, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressBetween(String value1, String value2) {
            addCriterion("customer_family_address between", value1, value2, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerFamilyAddressNotBetween(String value1, String value2) {
            addCriterion("customer_family_address not between", value1, value2, "customerFamilyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressIsNull() {
            addCriterion("customer_company_address is null");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressIsNotNull() {
            addCriterion("customer_company_address is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressEqualTo(String value) {
            addCriterion("customer_company_address =", value, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressNotEqualTo(String value) {
            addCriterion("customer_company_address <>", value, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressGreaterThan(String value) {
            addCriterion("customer_company_address >", value, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressGreaterThanOrEqualTo(String value) {
            addCriterion("customer_company_address >=", value, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressLessThan(String value) {
            addCriterion("customer_company_address <", value, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressLessThanOrEqualTo(String value) {
            addCriterion("customer_company_address <=", value, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressLike(String value) {
            addCriterion("customer_company_address like", value, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressNotLike(String value) {
            addCriterion("customer_company_address not like", value, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressIn(List<String> values) {
            addCriterion("customer_company_address in", values, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressNotIn(List<String> values) {
            addCriterion("customer_company_address not in", values, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressBetween(String value1, String value2) {
            addCriterion("customer_company_address between", value1, value2, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerCompanyAddressNotBetween(String value1, String value2) {
            addCriterion("customer_company_address not between", value1, value2, "customerCompanyAddress");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNull() {
            addCriterion("contract_name is null");
            return (Criteria) this;
        }

        public Criteria andContractNameIsNotNull() {
            addCriterion("contract_name is not null");
            return (Criteria) this;
        }

        public Criteria andContractNameEqualTo(String value) {
            addCriterion("contract_name =", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotEqualTo(String value) {
            addCriterion("contract_name <>", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThan(String value) {
            addCriterion("contract_name >", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameGreaterThanOrEqualTo(String value) {
            addCriterion("contract_name >=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThan(String value) {
            addCriterion("contract_name <", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLessThanOrEqualTo(String value) {
            addCriterion("contract_name <=", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameLike(String value) {
            addCriterion("contract_name like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotLike(String value) {
            addCriterion("contract_name not like", value, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameIn(List<String> values) {
            addCriterion("contract_name in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotIn(List<String> values) {
            addCriterion("contract_name not in", values, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameBetween(String value1, String value2) {
            addCriterion("contract_name between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractNameNotBetween(String value1, String value2) {
            addCriterion("contract_name not between", value1, value2, "contractName");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipIsNull() {
            addCriterion("contract_relation_ship is null");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipIsNotNull() {
            addCriterion("contract_relation_ship is not null");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipEqualTo(String value) {
            addCriterion("contract_relation_ship =", value, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipNotEqualTo(String value) {
            addCriterion("contract_relation_ship <>", value, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipGreaterThan(String value) {
            addCriterion("contract_relation_ship >", value, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipGreaterThanOrEqualTo(String value) {
            addCriterion("contract_relation_ship >=", value, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipLessThan(String value) {
            addCriterion("contract_relation_ship <", value, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipLessThanOrEqualTo(String value) {
            addCriterion("contract_relation_ship <=", value, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipLike(String value) {
            addCriterion("contract_relation_ship like", value, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipNotLike(String value) {
            addCriterion("contract_relation_ship not like", value, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipIn(List<String> values) {
            addCriterion("contract_relation_ship in", values, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipNotIn(List<String> values) {
            addCriterion("contract_relation_ship not in", values, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipBetween(String value1, String value2) {
            addCriterion("contract_relation_ship between", value1, value2, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractRelationShipNotBetween(String value1, String value2) {
            addCriterion("contract_relation_ship not between", value1, value2, "contractRelationShip");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneIsNull() {
            addCriterion("contract_mobile_phone is null");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneIsNotNull() {
            addCriterion("contract_mobile_phone is not null");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneEqualTo(String value) {
            addCriterion("contract_mobile_phone =", value, "contractMobilePhone");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneNotEqualTo(String value) {
            addCriterion("contract_mobile_phone <>", value, "contractMobilePhone");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneGreaterThan(String value) {
            addCriterion("contract_mobile_phone >", value, "contractMobilePhone");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("contract_mobile_phone >=", value, "contractMobilePhone");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneLessThan(String value) {
            addCriterion("contract_mobile_phone <", value, "contractMobilePhone");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("contract_mobile_phone <=", value, "contractMobilePhone");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneLike(String value) {
            addCriterion("contract_mobile_phone like", value, "contractMobilePhone");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneNotLike(String value) {
            addCriterion("contract_mobile_phone not like", value, "contractMobilePhone");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneIn(List<String> values) {
            addCriterion("contract_mobile_phone in", values, "contractMobilePhone");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneNotIn(List<String> values) {
            addCriterion("contract_mobile_phone not in", values, "contractMobilePhone");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneBetween(String value1, String value2) {
            addCriterion("contract_mobile_phone between", value1, value2, "contractMobilePhone");
            return (Criteria) this;
        }

        public Criteria andContractMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("contract_mobile_phone not between", value1, value2, "contractMobilePhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fct_customer_contract
     *
     * @mbg.generated do_not_delete_during_merge Sun May 13 13:36:11 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}