package com.kim.mapper;

import com.kim.model.FctCustomerContract;
import com.kim.model.FctCustomerContractExample;
import org.apache.ibatis.annotations.Param;

public interface FctCustomerContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    int insert(FctCustomerContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    int insertSelective(FctCustomerContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") FctCustomerContract record, @Param("example") FctCustomerContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") FctCustomerContract record, @Param("example") FctCustomerContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fct_customer_contract
     *
     * @mbg.generated Sun May 13 13:36:11 CST 2018
     */
    int updateByExample(@Param("record") FctCustomerContract record, @Param("example") FctCustomerContractExample example);
}